### ISSUE TITLE
Amendments for V0.0

### ISSUE THREAD

**Issue by titusong** [cs2103jan2015-w10-3c/main#20]
1)Optimise the space of the IU in case inputs are long
2)Content page should be only 1 page.
3)do not use #
4)Change modify to edit for a shorter word
5)User interface be more clear on the check function
6)Search change keyword to content.
7)Add User stories into the power point and user guide.
8)User must specify a storage location
9)Have a shortcut list
10)Include a Home List a week.
11)Create a prompt when overlapping task
12) Stronger Feedback for user
13) Welcome screen (Show todays)

Questions
How to change file location
If they dont specify time, How?
How to differentiate a timed task and deadline when user enters.

**Comment by ElaineCaiLingyi** [comment]
16) absolute path/ current working directory.--> can assume that user knows the path.  
(use powershell, cd ..)

17) floating task, shouldnt add time automatically. dont make too many assumptions for jim. but start time without end time (should extend one hour). 

18) can specify: add d, add t, add f.

**Comment by ElaineCaiLingyi** [comment]
joseph first 9, elaine last 9

**Comment by Josephgankh** [comment]
1, 2, 3, 4, 5, 8, 12, 18 completed

6) changed to keyword/s instead of content
7) added to user guide (except recurring)

**Comment by ElaineCaiLingyi** [comment]
10, 11, 16 completed

**Comment by ElaineCaiLingyi** [comment]
left with: 9, 13, 17

**Comment by ElaineCaiLingyi** [comment]
done 9, 17. left with: 13
